---
title: Toy example comparing EM vs. SCD
author: Peter Carbonetto
output: workflowr::wflow_html
---

ADD TEXT HERE.

```{r knitr-opts, include=FALSE}
knitr::opts_chunk$set(comment = "#",collapse = TRUE,results = "hold",
                      fig.align = "center",dpi = 120)
```

Load the packages used in the analysis below, as well as some
additional functions used to simulate the data and generate the results.

```{r load-pkgs, message=FALSE}
library(tm)
library(topicmodels)
library(fastTopics)
library(mvtnorm)
library(ggplot2)
library(cowplot)
source("../code/smallsim_functions.R")
```

ADD TEXT HERE.

```{r sim-data}
# Note: k should be 3 or greater.
simulate_correlated_loadings <- function (n, k) {
  L <- matrix(0,n,k)
  L[,1] <- runif(n,0,2)
  for (i in 1:n) {
    js <- sample(2:k,2)
    j1 <- js[1]
    j2 <- js[2]
    L[i,j1] <- 1
    L[i,j2] <- 0.1
  }
  return(normalize.rows(L))
}
set.seed(2)
n <- 100
m <- 400
k <- 6
F <- simulate_factors(m,k)
L <- simulate_correlated_loadings(n,k)
s <- simulate_sizes(n)
X <- simulate_multinom_counts(L,F,s)
X <- X[,colSums(X > 0) > 0]
```

ADD TEXT HERE.

```{r}
topic_colors <- c("dodgerblue","darkorange","forestgreen","darkblue",
                  "gold","skyblue")
simdata_structure_plot(L,topic_colors)
```

ADD TEXT HERE.

```{r}
control <- list(extrapolate = FALSE,numiter = 4)
fit0 <- fit_poisson_nmf(X,k,numiter = 20,method = "em",control = control)
fit1 <- fit_poisson_nmf(X,fit0=fit0,numiter=180,method="em",control=control)
fit2 <- fit_poisson_nmf(X,fit0=fit0,numiter=80,method="scd",control=control)
control$extrapolate <- TRUE
fit2 <- fit_poisson_nmf(X,fit0=fit2,numiter=100,method="scd",control=control)
fit0 <- poisson2multinom(fit0)
fit1 <- poisson2multinom(fit1)
fit2 <- poisson2multinom(fit2)
print(loadings_scatterplot(fit1$L,fit2$L,topic_colors,"em","scd"))
```

```{r}
pdat <- rbind(data.frame(iter   = 1:200,
                         ll     = fit1$progress$loglik.multinom,
                         res    = fit1$progress$res,
                         method = "em"),
			  data.frame(iter   = 1:200,
			             ll     = fit2$progress$loglik.multinom,
						 res    = fit2$progress$res,
						 method = "scd"))
pdat <- transform(pdat,
                  ll   = max(ll) - ll + 0.1)
p <- ggplot(pdat,aes(x = iter,y = ll,color = method)) +
  geom_line(size = 0.75) +
  scale_y_continuous(trans = "log10") +
  scale_color_manual(values = c("dodgerblue","darkorange")) +
  labs(x = "iteration",y = "loglik difference") +
  theme_cowplot(font_size = 10)
print(p)
```

```{r}
p1 <- simdata_structure_plot(L,topic_colors)
p2 <- simdata_structure_plot(fit1$L,topic_colors)
p3 <- simdata_structure_plot(fit2$L,topic_colors)
plot_grid(p1,p2,p3,nrow = 3,ncol = 1)
```
