---
title: A small simulation illustrating the trouble with EM
author: Peter Carbonetto
output: workflowr::wflow_html
---

*Add text here.*

```{r knitr-opts, include=FALSE}
knitr::opts_chunk$set(comment = "#",collapse = TRUE,results = "hold",
                      fig.align = "center",dpi = 120)
```

Load the packages used in the analysis below, as well as additional
functions that we will use to simulate the data.

```{r load-pkgs, message=FALSE}
library(fastTopics)
library(mvtnorm)
library(ggplot2)
library(cowplot)
source("../code/smallsim_functions.R")
```

Set the seed so that the results can be reproduced.

```{r set-seed}
set.seed(1)
```

Independent topics scenario
---------------------------

In this first example, we simulate a $100 \times 400$ counts matrix
from a multinomial topic model with $K = 6$ topics.

```{r simulate-data-1}
n <- 100
m <- 400
k <- 6
S <- 13*diag(k) - 2
F <- simulate_factors(m,k)
L <- simulate_loadings(n,k,S)
s <- simulate_sizes(n)
X <- simulate_multinom_counts(L,F,s)
X <- X[,colSums(X > 0) > 0]
```

The topic proportions for each of the 100 samples---that is, a row of
the counts matrix---are randomly drawn according to the
[correlated topic model](https://doi.org/10.1214/07-AOAS114): $\eta_i$
for row $i$ is drawn from the multivariate normal with mean zero and
covariance matrix $S$, such that $s_{kk} = 11$, $s_{jk} = -2$ for all
$j \neq k$. Generated in this way, the topic proportions tend to be
roughly orthogonal:

```{r structure-plot-1, fig.width=6, fig.height=1.5, message=FALSE}
y <- apply(L,1,which.max)
y <- rank(y,ties.method = "random")
y <- qqnorm(y,plot.it = FALSE)$x
fit <- list(L = L)
class(fit) <- c("multinom_topic_model_fit","list")
structure_plot(fit,topics = 1:6,perplexity = 30,Y_init = matrix(y),
               verbose = FALSE)
```

Here we compare two different updates for fitting a Poisson NMF model
to the simulated counts: EM updates, and sequential coordinate descent
(SCD). The model fitting is initialized by first running 50 EM
updates, with the aim of better ensuring that the same local maximum
is recovered by both runs.

```{r fit-1, results="hide", message=FALSE}
fit0 <- fit_poisson_nmf(X,k,numiter = 50,method = "em",
                        control = list(extrapolate = FALSE,numiter = 4))
fit1 <- fit_poisson_nmf(X,fit0 = fit0,numiter = 450,method = "em",
                        control = list(extrapolate = FALSE,numiter = 4))
fit2 <- fit_poisson_nmf(X,fit0 = fit0,numiter = 450,method = "scd",
                        control = list(extrapolate = FALSE,numiter = 4))
fit1 <- poisson2multinom(fit1)
fit2 <- poisson2multinom(fit2)
```

This next plot shows the improvement in the solution over time for the
EM and SCD updates.

```{r plot-progress-1, fig.width=3.5, fig.height=2.5}
pdat <- rbind(data.frame(x=1:500,y=fit1$progress$loglik.multinom,method="em"),
              data.frame(x=1:500,y=fit2$progress$loglik.multinom,method="scd"))
pdat <- transform(pdat,y = max(y) - y + 0.01)
pdat <- subset(pdat,x > 50)
ggplot(pdat,aes(x = x,y = y,color = method)) +
  geom_line(size = 0.75) +
  scale_y_continuous(trans = "log10",breaks = 10^seq(-2,3)) +
  scale_color_manual(values = c("dodgerblue","darkorange")) +
  labs(x = "iteration",y = "distance from best loglik") +
  theme_cowplot(font_size = 10)
```

Among the two methods compared, the SCD updates progresses more
rapidly toward a solution. Still, the EM updates recover the same
solution after a reasonable number of iterations. Next we will see an
example in which EM updates fail to make reasonable progress.

Correlated topics scenario
--------------------------

*Add text here.*

```{r simulate-data-2}
set.seed(1)
S[5,6] <- 10
S[6,5] <- 10
L <- simulate_loadings(n,k,S)
X <- simulate_multinom_counts(L,F,s)
X <- X[,colSums(X > 0) > 0]
```

TO DO: Plot mixture proportions for topics 5 and 6.

```{r structure-plot-2, fig.width=6, fig.height=1.5, message=FALSE}
y <- apply(L,1,which.max)
y <- rank(y,ties.method = "random")
y <- qqnorm(y,plot.it = FALSE)$x
fit <- list(L = L)
class(fit) <- c("multinom_topic_model_fit","list")
structure_plot(fit,topics = 1:6,perplexity = 30,Y_init = matrix(y),
               verbose = FALSE)
```

```{r fit-5, results="hide", message=FALSE}
fit0 <- fit_poisson_nmf(X,k,numiter = 50,method = "em",
                        control = list(extrapolate = FALSE,numiter = 4))
fit1 <- fit_poisson_nmf(X,fit0 = fit0,numiter = 800,method = "em",
                        control = list(extrapolate = FALSE,numiter = 4))
fit2 <- fit_poisson_nmf(X,fit0 = fit0,numiter = 1000,method = "scd",
                        control = list(extrapolate = FALSE,numiter = 4))
fit3 <- fit_poisson_nmf(X,fit0 = fit1,numiter = 200,method = "scd",
                        control = list(extrapolate = FALSE,numiter = 4))
fit1 <- fit_poisson_nmf(X,fit0 = fit1,numiter = 200,method = "scd",
                        control = list(extrapolate = FALSE,numiter = 4))
```

*Add text here.*

```{r plot-progress-2, fig.width=4, fig.height=3}
fit1 <- poisson2multinom(fit1)
fit2 <- poisson2multinom(fit2)
fit3 <- poisson2multinom(fit3)
plot_progress(list(em = fit1,scd = fit2,"scd+em" = fit3),
              x = "iter",add.point.every = 100)
```
